### ISSUE TITLE
rebuild with ExpressJS

### ISSUE THREAD

**Issue by curlynux** [jasonjoh/node-tutorial#15]
hi, can you rebuild this nice tutorial with ExpressJS ?, which is much more readable and not fastidious to write than pure Node code,

thank's.

**Comment by jasonjoh** [comment]
Thanks for the suggestion @curlynux. While it's a good suggestion (I love ExpressJS!), I'm not going to rebuild it. This tutorial was more about using the Outlook API, not building a web app. Hopefully with the info here you can easily build your own ExpressJS app that calls the Outlook API :).

**Comment by curlynux** [comment]
thank you for reply ! :) say that because i try to setup a contact form
with ejs and express but, my nodemailer script return me an error even if
the code is good outlook hotmail both not work with my nodemailer script.
and your nodejs tutorial syntax is hard for le cuz i'm noob with nodejs
itself not with express. Sorry if my english is bad i'm french xD

Le jeu. 23 mars 2017 à 16:32, Jason Johnston <notifications@github.com> a
écrit :

**Comment by curlynux** [comment]
every change i made return the same error, can't send from my contact form
to my outlook email

Le jeu. 23 mars 2017 à 16:48, Ibrahim Touré(sam) <smpunchack@gmail.com> a
écrit :
