### ISSUE TITLE
sample doesnt work use to wrong field accessed in getUserEmail function

### ISSUE THREAD

**Issue by indolent-developer** [jasonjoh/node-tutorial#16]
since res.mail is empty the code just hangs. Replaced with userPrincipalName and its works fine.

client
    .api('/me')
    .get((err, res) => {
      if (err) {
        callback(err, null);
      } else {
        ~callback(null, res.mail);~
        callback(null, res.userPrincipalName);
      }
    });

**Comment by jasonjoh** [comment]
I'm guessing you're using an Outlook.com account? I reproduce it there but not with an Office 365 account. I'll follow up and find out why this is happening.

**Comment by indolent-developer** [comment]
Thanks ! Yes it was outlook.com account.

**Comment by jasonjoh** [comment]
Thanks for verifying. This is a problem with the Graph right now. I'm still following up with the Graph devs on what the correct way to handle this should be. My concern with using `userPrincipalName` is I'm not 100% sure it is guaranteed to always be an SMTP address (e.g. if user signs in with a mobile phone number, for example).

**Comment by jasonjoh** [comment]
UPDATE: I did chat with the Graph devs and for Microsoft accounts (Outlook.com) `userPrincipalName` should always be their SMTP address.

**Comment by indolent-developer** [comment]
Thanks ! That was quick :)

**Comment by jasonjoh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Do the thing!](https://trello.com/c/01vGDTwm/1-do-the-thing)
