### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Sushi21** [jasonjoh/node-tutorial#25]
I just downloaded the example to do a quick test but it doesn't start.

![image](https://user-images.githubusercontent.com/35455125/39942005-9ae86468-5534-11e8-9db2-fd491ebde342.png)

**Comment by jasonjoh** [comment]
Did you do `npm install` by chance?

**Comment by Sushi21** [comment]
I found the issue. My version of node js was too old and didn't support aync function at that time.

**Comment by jasonjoh** [comment]
Ah ok, great! Glad you got that sorted out.
