### ISSUE TITLE
Error status code: undefined

### ISSUE THREAD

**Issue by imalbert** [jasonjoh/node-tutorial#26]
I'm getting this kind of error on graph client requests only when using my ms work account (personal account requests returns as expected).

request:
```
const result = await client
  .api('/me/mailfolders/inbox/messages')
  .top(10)
  .select('subject,from,receivedDateTime,isRead')
  .orderby('receivedDateTime DESC')
  .get();
```

returns an error
```
{
  statusCode: undefined,
  code: null,
  message: null,
  requestId: null,
  date: 2018-07-26T07:53:06.093Z,
  body: null
}
```

Hope anyone could help!

**Comment by jasonjoh** [comment]
I suggest going to the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and logging in with that same account, then see if you can get your messages in the tool. I've never seen this behavior before.

**Comment by imalbert** [comment]
It does work fine on Graph Explorer. I'll continue investigating. I'm suspecting it's an issue with my proxy.
