### ISSUE TITLE
Authentication works but Inbox nav item is not displayed and cannot get to localhost:3000/mail

### ISSUE THREAD

**Issue by jmalla** [jasonjoh/node-tutorial#28]
I am following the tutorial.  The authentication is working.  However, I do not get the Inbox nav item.  I tried to go to localhost:3000/mail and that did not work. 

I am not sure why this is not working.  I have looked through the code and not able to see how the logic works to display the Inbox nav item.

Thanks,
Jay

**Comment by jmalla** [comment]
Not an issue.  This issue can be deleted.

**Comment by jasonjoh** [comment]
Thanks @jmalla! You also reported this in the documentation repository (https://github.com/OfficeDev/outlook-dev-docs/issues/417). Should that one be closed too?
