### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by Leon-Atrish** [jasonjoh/node-tutorial#29]
I am not able to login via the link generated to verify app. Please check screenshot for reference:

<img width="1440" alt="screen shot 2018-11-10 at 12 17 30 am" src="https://user-images.githubusercontent.com/35444609/48282846-d678fc00-e480-11e8-9855-d7872b1d31d2.png">

**Comment by jasonjoh** [comment]
Examine the URL closely, it contains an error_description that should point you to the problem. It looks like your redirect URI isn't correct.

**Comment by Leon-Atrish** [comment]
my bad! found it. Thanks ;)

**Comment by jasonjoh** [comment]
What do you have registered on your app registration, can you post a screenshot?

**Comment by Leon-Atrish** [comment]
Its still not working! yeah wait.

**Comment by Leon-Atrish** [comment]
Is this what you want?

<img width="1440" alt="screen shot 2018-11-10 at 1 03 53 am" src="https://user-images.githubusercontent.com/35444609/48284144-987dd700-e484-11e8-81a7-1985d27ad512.png">

**Comment by jasonjoh** [comment]
Yep. Now what is the auth URL that gets generated by the app?

**Comment by Leon-Atrish** [comment]
Can you please help me out? I am able to login now and  I am getting undefined details of my account but getting access token.

**Comment by Leon-Atrish** [comment]
and this is the URL: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=0e006ac7-658e-4e75-981b-5d46962ab49c&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauthorize&scope=openid%20profile%20offline_access%20User.Read%20Mail.Read%20Calendars.Read%20Contacts.Read

**Comment by jasonjoh** [comment]
Where exactly is it giving undefined details?

**Comment by Leon-Atrish** [comment]
<img width="1440" alt="screen shot 2018-11-12 at 9 21 13 pm" src="https://user-images.githubusercontent.com/35444609/48358578-0e6e8200-e6c1-11e8-9a5a-51239d74b7ab.png">

**Comment by Leon-Atrish** [comment]
Hi Jason,
The demo is working now. But if you could help me to provide code to send emails then that would be really grateful.

**Comment by Leon-Atrish** [comment]
> Where exactly is it giving undefined details?



> Where exactly is it giving undefined details?

Actually, my name on the account wasn't setup that's why it was showing undefined. My bad.

**Comment by Leon-Atrish** [comment]
I can't find the code and any way to send an email, could you help me out?

**Comment by jasonjoh** [comment]
Sorry I don't have that code readily available. The docs are here: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/message_send. There is a sample of sending mail on the SDK's GitHub page here: https://github.com/microsoftgraph/msgraph-sdk-javascript#post-and-patch
