### ISSUE TITLE
"Bad Request"  response when email scope is added

### ISSUE THREAD

**Issue by thomasmurphycodes** [jasonjoh/node-tutorial#3]
I'm modifying an app to reflect the new Authentication Protocol (https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-preview-oidc-changes/)

However, when I add e-mail to the array of scopes, my call to **oauth2.authCode.getToken** returns Bad Request. This issue is not present when "email" is not part of the array of the scopes.

Works:
`var scopes = [ "openid",
               "https://outlook.office.com/mail.read"];`

Broken:
`var scopes = [ "openid",
               "https://outlook.office.com/mail.read", "email"];`

**Comment by jasonjoh** [comment]
I'll take a look as soon as I can. In the meantime are you able to get a network trace of this failure? I'd be interested in what the actual request/response looks like.

**Comment by jasonjoh** [comment]
I never could reproduce this. If you still have this problem, please let me know.

**Comment by thomasmurphycodes** [comment]
I unfortunately got pulled onto another project right when I was starting to work on this so never got to dig deeper.
