### ISSUE TITLE
Everything works well on localhost but in production it doesn't work

### ISSUE THREAD

**Issue by Leon-Atrish** [jasonjoh/node-tutorial#30]
PRODUCTION ENVIRONMENT:
app.js is running on 3000 port but it opens using http not https.
why it redirects on our website instead of microsoft page unlike gmail api, it redirect us to google's webpage for access token?

**Comment by jasonjoh** [comment]
Using http and port 3000 is default Express stuff. You need to head over to http://expressjs.com/ and read their docs on deploying to production, setting up SSL certificates, etc.
