### ISSUE TITLE
Need admin approval?

### ISSUE THREAD

**Issue by muhualing** [jasonjoh/node-tutorial#33]
I try to run the sample, when I log in, this appears, I don't know how to deal with it.
![image](https://user-images.githubusercontent.com/12086605/58631223-73fc2600-8314-11e9-8885-1134f3b218c1.png)

**Comment by jasonjoh** [comment]
Looks like you're using a corporate microsoft.com account. Our IT has disabled user ability to consent to any apps that they haven't reviewed and approved. You'll need to use a demo tenant or an outlook.com account to test.
