### ISSUE TITLE
PolyFillNotAvailable

### ISSUE THREAD

**Issue by binli0114** [jasonjoh/node-tutorial#34]
Error occurs when clicks the mail button.

> (node:960) UnhandledPromiseRejectionWarning: PolyFillNotAvailable: Library cannot function without fetch. So, please provide polyfill for it.  

Solution:
npm install --save isomorphic-fetch
Then
`require("isomorphic-fetch");` in mail.js

**Comment by jasonjoh** [comment]
Closing this issue as I'm archiving this sample. We've retired the tutorial that this is based on and we're redirecting to the Microsoft Graph tutorial at https://docs.microsoft.com/graph/tutorials/node. The corresponding GitHub repo is https://github.com/microsoftgraph/msgraph-training-nodeexpressapp
