### ISSUE TITLE
GetEmailFromId not returning user or email

### ISSUE THREAD

**Issue by tjk911** [jasonjoh/node-tutorial#4]
I'm not 100% this is where the error is occurring, so do forgive me if I'm wrong.

`GetTokenFromCode` works, I get a token and console tells me that I've created a Token. I see the _type, scope, expiration, and access_token_ and _id_token field_.

Passing it to `getEmailFromIdToken` however, _jwt.preferred_username_ is returning as **undefined**.

I logged _jwt_ and I'm seeing these fields and no preferred_username;

`{ aud: 'xxxx',
  iss: 'xxxx',
  iat: xxxx,
  nbf: xxxx,
  exp: xxxx,
  ipaddr: '000.000.000.000',
  sub: 'xxxx',
  tid: 'xxxx',
  ver: '2.0' }
`

`token.token.access_token` returns the entire id_token field, while `authHelper.getEmailFromIdToken(token.token.id_token)` returns undefined.

I'm baffled.

**Comment by tjk911** [comment]
Never mind, I'm a dumbass. I didn't set the cookies properly. I'm still unsure why I'm getting undefined, but it works!

**Comment by jasonjoh** [comment]
Make sure that you include the `profile` scope when doing auth. Azure won't return `preferred_username` unless you have that scope.

**Comment by tjk911** [comment]
Thanks again Jason! I'll look into that. I'm also having issues refreshing my token, just a pre-emptive heads up I might open another issue later today/tomorrow.
